version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: digital_credit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_credit_client
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Bull Queue
  redis:
    image: redis:7-alpine
    container_name: digital_credit_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Client Backend
  client-backend:
    build:
      context: ./client-app/backend
      dockerfile: Dockerfile
    container_name: client_backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: digital_credit_client
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-change-me}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-refresh-secret-change-me}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Client Frontend
  client-frontend:
    build:
      context: ./client-app/frontend
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - "3000:80"
    depends_on:
      - client-backend
    restart: unless-stopped

  # Admin Backend
  admin-backend:
    build:
      context: ./admin-app/backend
      dockerfile: Dockerfile
    container_name: admin_backend
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: digital_credit_client
      JWT_SECRET: ${ADMIN_JWT_SECRET:-your-admin-jwt-secret-change-me}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

